name: Binary Uploader

on:
  release:
    types: [edited]

env:
  PROC_NAME: ssh-conf-cli
  WIN_BUILD_NAME: win_amd64
  LINUX_BUILD_NAME: linux_amd64
  BUILD_OPTION: -ldflags '-s -w' 
  VERSION_VARIALBE: github.com/quag-cactus/ssh-conf-cli/cmd.version

jobs:
  build:
    name: Build release binary
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Get release info
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build binary
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Preparation for Build
        run: |
          mkdir -p bin/${{ env.WIN_BUILD_NAME }}/
          mkdir -p bin/${{ env.LINUX_BUILD_NAME }}/
  
      - name: Build for Windows
        run: >
          GOOS=windows GOARCH=amd64 
          go build 
          -v -ldflags '-s -w -X ${{ env.VERSION_VARIALBE }}=${{ steps.get_release.outputs.tag_name }}' -trimpath
          -o bin/${{ env.WIN_BUILD_NAME }}/ ./...

      - name: Build for Linux
        run: >
          GOOS=linux GOARCH=amd64 
          go build 
          -v -ldflags '-s -w -X ${{ env.VERSION_VARIALBE }}=${{ steps.get_release.outputs.tag_name }}' -trimpath
          -o bin/${{ env.LINUX_BUILD_NAME }}/ ./... 

      - name: Set zip-file names
        run: |
          echo "WIN_ZIP_NAME=${{ env.PROC_NAME }}_${{ env.WIN_BUILD_NAME }}_${{ steps.get_release.outputs.tag_name }}.zip" >> $GITHUB_ENV
          echo "LINUX_ZIP_NAME=${{ env.PROC_NAME }}_${{ env.LINUX_BUILD_NAME }}_${{ steps.get_release.outputs.tag_name }}.zip" >> $GITHUB_ENV

      - name: Zip for Windows
        working-directory: ./bin/${{ env.WIN_BUILD_NAME }}
        run: |
          zip -r ${{ env.WIN_ZIP_NAME }} ./*
          mv ${{ env.WIN_ZIP_NAME }} ${{ github.workspace }}
  
      - name: Zip for Linux
        working-directory: ./bin/${{ env.LINUX_BUILD_NAME }}
        run: |
          zip -r ${{ env.LINUX_ZIP_NAME }} ./*
          mv ${{ env.LINUX_ZIP_NAME }} ${{ github.workspace }}

      - name: Upload Release Asset for Windows
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ env.WIN_ZIP_NAME }}
          asset_content_type: application/zip
          overwrite: true

      - name: Upload Release Asset for Linux
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ env.LINUX_ZIP_NAME }}
          asset_content_type: application/zip
          overwrite: true
