name: Auto Deploy
run-name: ${{ github.actor }} is deploying ${{ github.repository }}
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Version
        uses: echo ${GITHUB_REF##*/}